export const groceriesItem = [
  // cigaretes

  {
    id: 1,
    name: "surya 16",
    category: "cigaretes",
    rating: 4.3,
    price: 32000,
    img: "image/Cigarettes/surya16.jpg",
    quantity: 1,
  },
  {
    id: 2,
    name: "surya 12",
    category: "cigaretes",
    rating: 4.3,
    price: 23000,
    img: "image/Cigarettes/surya12.jpg",
    quantity: 1,
  },
  {
    id: 3,
    name: "juara",
    category: "cigaretes",
    rating: 4.3,
    price: 23000,
    img: "image/Cigarettes/juara.jpg",
    quantity: 1,
  },
  {
    id: 4,
    name: "Gajah Baru",
    category: "cigaretes",
    rating: 4.3,
    price: 18000,
    img: "image/Cigarettes/gajahBaru.jpg",
    quantity: 1,
  },
  {
    id: 5,
    name: "Djarum Super",
    category: "cigaretes",
    rating: 4.3,
    price: 20000,
    img: "image/Cigarettes/DjarumSuper.jpg",
    quantity: 1,
  },
  {
    id: 6,
    name: "Djarum 76",
    category: "cigaretes",
    rating: 4.3,
    price: 15000,
    img: "image/Cigarettes/Djarum76.jpg",
    quantity: 1,
  },
  {
    id: 7,
    name: "Marlboro Black",
    category: "cigaretes",
    rating: 4.3,
    price: 25000,
    img: "image/Cigarettes/marlboroBlack.jpg",
    quantity: 1,
  },
  {
    id: 8,
    name: "Marlboro",
    category: "cigaretes",
    rating: 4.3,
    price: 40000,
    img: "image/Cigarettes/marlboro.jpg",
    quantity: 1,
  },
  {
    id: 9,
    name: "Sampoerna",
    category: "cigaretes",
    rating: 4.3,
    price: 33000,
    img: "image/Cigarettes/sampoerna.jpg",
    quantity: 1,
  },
  {
    id: 10,
    name: "Dji Sam Soe",
    category: "cigaretes",
    rating: 4.3,
    price: 20000,
    img: "image/Cigarettes/DjiSamSoe.jpg",
    quantity: 1,
  },

  // Groceries

  {
    id: 11,
    name: "Beras",
    category: "groceries",
    rating: 4.3,
    price: 60000,
    img: "image/Groceries/Beras.jpg",
    quantity: 1,
  },
  {
    id: 12,
    name: "Galon",
    category: "groceries",
    rating: 4.3,
    price: 20000,
    img: "image/Groceries/galon.jpg",
    quantity: 1,
  },
  {
    id: 13,
    name: "Garam",
    category: "groceries",
    rating: 4.3,
    price: 7000,
    img: "image/Groceries/garam.jpg",
    quantity: 1,
  },
  {
    id: 14,
    name: "Gula",
    category: "groceries",
    rating: 4.3,
    price: 15000,
    img: "image/Groceries/Gula.jpg",
    quantity: 1,
  },
  {
    id: 15,
    name: "Kecap",
    category: "groceries",
    rating: 4.3,
    price: 9000,
    img: "image/Groceries/Kecap.jpg",
    quantity: 1,
  },
  {
    id: 16,
    name: "LPG",
    category: "groceries",
    rating: 4.3,
    price: 20000,
    img: "image/Groceries/Lpg.jpg",
    quantity: 1,
  },
  {
    id: 17,
    name: "Mie Goreng",
    category: "groceries",
    rating: 4.3,
    price: 2500,
    img: "image/Groceries/MieGoreng.jpg",
    quantity: 1,
  },
  {
    id: 18,
    name: "Minyak",
    category: "groceries",
    rating: 4.3,
    price: 40000,
    img: "image/Groceries/minyak.jpg",
    quantity: 1,
  },
  {
    id: 19,
    name: "Saus",
    category: "groceries",
    rating: 4.3,
    price: 20000,
    img: "image/Groceries/Saus.jpg",
    quantity: 1,
  },
  {
    id: 20,
    name: "Telur",
    category: "groceries",
    rating: 4.3,
    price: 20000,
    img: "image/Groceries/Telur.jpg",
    quantity: 1,
  },

  // Snack

  {
    id: 21,
    name: "Chiki Balls",
    category: "snack",
    rating: 4.3,
    price: 2000,
    img: "image/Snack/Chikiballs.jpg",
    quantity: 1,
  },
  {
    id: 22,
    name: "Crackers",
    category: "snack",
    rating: 4.3,
    price: 7000,
    img: "image/Snack/crackers.jpg",
    quantity: 1,
  },
  {
    id: 23,
    name: "Happytos",
    category: "snack",
    rating: 4.3,
    price: 10000,
    img: "image/Snack/Happytos.jpg",
    quantity: 1,
  },
  {
    id: 24,
    name: "Komo",
    category: "snack",
    rating: 4.3,
    price: 1000,
    img: "image/Snack/komo.jpg",
    quantity: 1,
  },
  {
    id: 25,
    name: "Lays",
    category: "snack",
    rating: 4.3,
    price: 2000,
    img: "image/Snack/lays.jpg",
    quantity: 1,
  },
  {
    id: 26,
    name: "Malkist",
    category: "snack",
    rating: 4.3,
    price: 5000,
    img: "image/Snack/malkist.jpg",
    quantity: 1,
  },
  {
    id: 27,
    name: "Mie Enaak",
    category: "snack",
    rating: 4.3,
    price: 1000,
    img: "image/Snack/mieenaak.jpg",
    quantity: 1,
  },
  {
    id: 28,
    name: "Mie Kremes",
    category: "snack",
    rating: 4.3,
    price: 500,
    img: "image/Snack/miekremes.jpg",
    quantity: 1,
  },
  {
    id: 29,
    name: "Taro",
    category: "snack",
    rating: 4.3,
    price: 2000,
    img: "image/Snack/Taro.jpg",
    quantity: 1,
  },
  {
    id: 30,
    name: "TicTac",
    category: "snack",
    rating: 4.3,
    price: 2000,
    img: "image/Snack/tictac.jpg",
    quantity: 1,
  },

  // Drink

  {
    id: 31,
    name: "Cincau",
    category: "drink",
    rating: 4.3,
    price: 8000,
    img: "image/Drink/Cincau panda.jpg",
    quantity: 1,
  },
  {
    id: 32,
    name: "Floridina",
    category: "drink",
    rating: 4.3,
    price: 3000,
    img: "image/Drink/Floridina.jpg",
    quantity: 1,
  },
  {
    id: 33,
    name: "Fruittea",
    category: "drink",
    rating: 4.3,
    price: 4000,
    img: "image/Drink/fruittea.jpg",
    quantity: 1,
  },
  {
    id: 34,
    name: "Good Day",
    category: "drink",
    rating: 4.3,
    price: 8000,
    img: "image/Drink/Goodday.jpg",
    quantity: 1,
  },
  {
    id: 35,
    name: "Hydrococo",
    category: "drink",
    rating: 4.3,
    price: 7000,
    img: "image/Drink/Hydrococo.jpg",
    quantity: 1,
  },
  {
    id: 36,
    name: "Kapalapi",
    category: "drink",
    rating: 4.3,
    price: 5000,
    img: "image/Drink/Kapalapi.jpg",
    quantity: 1,
  },
  {
    id: 37,
    name: "Kopi ABC",
    category: "drink",
    rating: 4.3,
    price: 3000,
    img: "image/Drink/Kopiabc.jpg",
    quantity: 1,
  },
  {
    id: 38,
    name: "Larutan",
    category: "drink",
    rating: 4.3,
    price: 7000,
    img: "image/Drink/Larutan.jpg",
    quantity: 1,
  },
  {
    id: 39,
    name: "Teh Pucuk",
    category: "drink",
    rating: 4.3,
    price: 3000,
    img: "image/Drink/Pucuk.jpg",
    quantity: 1,
  },
  {
    id: 40,
    name: "Pulpy Orange",
    category: "drink",
    rating: 4.3,
    price: 6000,
    img: "image/Drink/Pulpy.jpg",
    quantity: 1,
  },
];
